# Generated by Django 3.1.7 on 2021-03-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_category_gifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uploader_name',
        ),
    ]
