# Generated by Django 3.1.7 on 2021-03-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210304_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='field_name',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
