# Generated by Django 3.1.7 on 2021-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210305_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
